---
spring:
  config.activate.on-profile: default
  web.resources.static-locations: "file:./app"
  sql:
    init:
      mode: never
  datasource:
    url: "jdbc:sqlite:sqlite.db"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
cds:
  datasource:
    auto-config.enabled: false
  security:
    mock:
      defaultUsers: false
dms:
  type: local
  target:
    folder: /tmp
    credentials-file: ""
security:
  credentials-file: "./srv/src/main/resources/creds.json"
server:
  port : 8082
