---
spring:
  config.activate.on-profile: default
  web.resources.static-locations: "file:./app"
  sql:
    init:
      mode: never
  datasource:
    url: "jdbc:sqlite:sqlite.db"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
cds:
  datasource:
    auto-config.enabled: false
  security:
    mock:
      defaultUsers: false

  remote.services:
  - name: "com.sap.gateway.srvd_a2x.zykza_threadheader_api_def.v0001"
    model: "com.sap.gateway.srvd_a2x.zykza_threadheader_api_def.v0001"
    destination:
      name: "s4-rap-replicator-api"
      type: "odata-v4"
      retrievalStrategy: "AlwaysProvider"

workflow:
  uri: ""
  credentials: ""
dms:
  type: local
  target:
    folder: /tmp
    credentials-file: ""
security:
  credentials-file: "./srv/src/main/resources/creds.json"
server:
  port : 8082
